title: Rachit Shaha
logo: /assets/img/headshot_circle.JPG
description: Dedicated Software Engineer with expertise in AI, ML, and Distributed Systems, aiming to leverage skills in algorithm development and model optimization. Eager to contribute to innovative projects, enhancing product performance and user experience through advanced computational techniques. <br><br><br><br>
#show_downlaods: True
theme: jekyll-theme-minimal
